### ISSUE TITLE
dsyMatrix is not supported

### ISSUE THREAD

**Issue by wanpinglee** [xihaoli/STAARpipeline-Tutorial#4] opened 2022-08-15 18:42 UTC
Dear authors,

Thank you so much for developing the tool. After I created aGDS, I encountered an error of "dsyMatrix is not supported" when performing STAARpipeline_Gene_Centric_Noncoding.r.

The complete error message is
```
Error in STAAR_O_SMMAT_sparse(G, Sigma_i, Sigma_iX, cov, residuals.phenotype,  :
  dsyMatrix is not supported.
```

Any idea how to fix the issue Thanks!

Best,

**Comment by xihaoli** [comment] 2022-08-16 02:16
Hi Wan-ping,

Thanks for your question. Did you run your analysis and encounter this issue based on this [dockerized R environment](https://hub.docker.com/r/zilinli/staarpipeline)? Were you able to run individual analysis (Step 2) using STAARpipeline?

If not, could you please check and let us know your `R` version and `sessionInfo()`?

Please feel free to let me know if you have any additional questions.

Best,
Xihao

**Comment by wanpinglee** [comment] 2022-08-16 14:27
Hi Xihao,

Thanks so much for your help.
No, I couldn't perform individual analysis either. The same error. My R session is shown below.

```
> sessionInfo()
R version 4.2.0 (2022-04-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.4 LTS

Matrix products: default
BLAS:   /usr/local/R4/lib/R/lib/libRblas.so
LAPACK: /usr/local/R4/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.2.0

```

Best,
Wan-Ping

**Comment by xihaoli** [comment] 2022-08-19 04:07
Hi Wan-Ping,

Upon discussion, the issue is on the class (type) of `Sigma_i` from the null model object `obj_nullmodel`, which can be fixed by setting `as(Sigma_i, ’dsCMatrix’)`.

Best,
Xihao

**Comment by xihaoli** [comment] 2022-08-19 04:08
Hi Wan-Ping,

Upon discussion, the issue is on the class (type) of `Sigma_i` from the null model object `obj_nullmodel`, which can be fixed by setting `as(Sigma_i, "dsCMatrix")`.

Best,
Xihao

**Comment by wanpinglee** [comment] 2022-08-19 12:27
Thanks, Xihao.

**Closed** 2022-08-19 13:11 UTC
